services:
  db:
    image: postgres:15-alpine
    container_name: mimo_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mimo_pass
      - POSTGRES_DB=mimodigital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: